spring:
  datasource:
    url: jdbc:mysql://localhost:3306/connectium?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: connectium
    password: connectium
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          characterEncoding: utf8
          useUnicode: true
  web:
    locale: en_US
    locale-resolver: fixed
  mvc:
    log-resolved-exception: true
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.ohgiraffers.crud_back: DEBUG

ftp:
  server: 1.214.19.22
  port: 2121
  username: connectium
  password: connectium
  in-path: /HOMEPAGE/PROGRAM/IN/
  out-path: /HOMEPAGE/PROGRAM/OUT/
  connect-timeout: 5000
  data-timeout: 10000

image:
  storage:
    path: ${java.io.tmpdir}/program_images

openapi:
  key: 775276464663616e3736627a6b7a47
  key2: 787650664663616e333645424e6d56
  base-url: http://openAPI.seoul.go.kr:8088/

jwt:
  secret: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  expiration: 7200

weather:
  api:
    key: "oYlZ3s12CCpWogr488cJRvx1CrjY9jPOWhM6xkj8kD3gb%2BKmo8MNFhCEu%2FCNrJ5B%2Fla40ocHY5AtQBod2%2Fw69Q%3D%3D"
    url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"
    data-type: JSON
    num-of-rows: 10
    page-no: 1
    default:
      nx: 62
      ny: 128